# Ruby Gems for building and testing Bootstrap
# Run `grunt update-gemfile-lock` to update to the latest compatible versions

source 'https://rubygems.org'

group :development, :test do
  gem 'listen', '~> 2.4'
  gem 'wdm', '>= 0.1.0'
  gem 'jekyll', '~> 2.5.2'
  gem 'rouge', '~> 1.7.4'
  gem 'sass', '~> 3.4.9'
  gem 'scss-lint', '~> 0.31'
end
